Problem: We would like to use tabs in ZPL configs.
42ity/czmq pull request #5
Opened 2018-02-07 14:57 UTC by jana-rapava

Solution: Add the support, count tab as 1 level / 4 spaces.

Signed-off-by: Jana Rapava <janarapava@eaton.com>

2018-02-07 15:14 UTC, michal42 commented
Are you going to submit this to upstream czmq?

2018-02-07 15:22 UTC, michal42 requested changes
Please submit the change to https://github.com/zeromq/czmq, otherwise we will have to redo it when we update our czmq copy.

2018-02-08 09:42 UTC, jimklimov commented
I'll take care of resubmission to upstream, thanks for the notice.

2018-02-08 09:42 UTC, merged

2018-02-08 09:45 UTC, jimklimov commented
Reposted to upstream at https://github.com/zeromq/czmq/pull/1842